export const ENV_VARS_NAMES = {
  PORT: 'PORT',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
};

export const ENV_AMQP = {
  RABBITMQ_USER: 'RABBITMQ_USER',
  RABBITMQ_PASSWORD: 'RABBITMQ_PASSWORD',
  RABBITMQ_HOST: 'RABBITMQ_HOST',
  RABBITMQ_QUEUE_NAME: 'RABBITMQ_QUEUE_NAME',
};
